# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
 twitter_api_key: '5DrDw2JpX4tP7EpmZbBsxuTvL'
 twitter_api_secret: 'CEXDhZQTy62SxWqfUxy8SkpRUgjAP8higOFmKhXktRAPbRrAK6'

default_facebook: &default_facebook
 facebook_api_key: '1656885284561882'
 facebook_api_secret: '107ba675a2f9894f69a4dc939d46579e'

development:
  secret_key_base: bdeb76fbdc8e1bbf828fbaa3c9679cd414c6ba2d316e6530f1a228eb0f930d2238a3d55e4a183bd92c11fde90ca0ea4ed3d28daac3c7b30a7da4e64fd2f47e7b
  <<: *default_twitter
  <<: *default_facebook
  
test:
  secret_key_base: 963a058b748587d2375590590065046e5eaff68e2ee604242037b7eeda607fa1dd1840943a09df285da973d05cf4789c3b24fcd4c51a0502dfe951ca0bf613e9
  <<: *default_twitter
  <<: *default_facebook

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%=ENV["TWITTER_CONSUMER_SECRET"] %>
  facebook_api_key: <%= ENV["FACEBOOK_CONSUMER_KEY"] %>
  facebook_api_secret: <%=ENV["FACEBOOK_CONSUMER_SECRET"] %>
